### ISSUE TITLE
Can't export save files (System.IO.InvalidDataException: File 'meta.lsf' has unsupported flags: 35) LSF v9?

### ISSUE THREAD

**Issue by Minirig355** [LennardF1989/BG3-ImHex-Patterns#3]
Unfortunately it has an issue and I can't export save files. I feel like this has something to do with the implementation of LSF v9 but I'm not as knowledgeable as you and the others who worked on cracking NewAge, I'm just someone hoping to add the Summon Shovel scroll into my inventory after someone in my game used it before my wizard :( still, great work.

Worth noting LSLib had the same error on their stable version (1.18.7) but fixed it as of the beta (1.19.3), however 1.19.2 has not fixed this, leading me to believe it's the v7/v9 update. Here's the error output in cmd:

```
Unhandled exception. System.IO.InvalidDataException: File 'meta.lsf' has unsupported flags: 35
   at LSLib.LS.PackagedFileInfo.CreateFromEntry(FileEntry18 entry, Stream dataStream)
   at LSLib.LS.PackageReader.ReadFileListV18(BinaryReader reader, Package package)
   at LSLib.LS.PackageReader.ReadPackageV18(FileStream mainStream, BinaryReader reader)
   at LSLib.LS.PackageReader.Read()
   at BG3.Extractor.Program.Main(String[] args) in C:\Users\Lennard\Desktop\BG3-ImHex-Patterns\Src\BG3.Extractor\Program.cs:line 14```

**Comment by clemarescx** [comment]
The latest hotfix (17) introduced a third compression method, ZSTD, which is compression flag 0x23, i.e 35 (ZLIB was 0x21, LZ4 was 0x22). 
It's been implemented upstream on LSLib main, but this extractor uses Lennard's .NET 6 fork of LSLib that hasn't been updated for a while and therefore doesn't know about ZSTD.

edit: fixed the hex flags, can't brain on Sundays...
